# Site settings
title: Veri Bilimi Notlarım
email: mert.nuhoglu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Veri bilimi çalışma ve notlarım
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://veribilimi.mertnuhoglu.com" # the base hostname & protocol for your site
twitter_username: mertnuhoglu
github_username:  mertnuhoglu

# Build settings
markdown: kramdown

google_analytics: 'UA-20351819-9'
